# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6262, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from typing import TYPE_CHECKING

from azure.core import PipelineClient
from msrest import Deserializer, Serializer

if TYPE_CHECKING:
    # pylint: disable=unused-import,ungrouped-imports
    from typing import Any

from ._configuration import AzureWebSocketServiceRESTAPIConfiguration
from .operations import HealthApiOperations
from .operations import WebSocketConnectionApiOperations


class AzureWebSocketServiceRESTAPI(object):
    """AzureWebSocketServiceRESTAPI.

    :ivar health_api: HealthApiOperations operations
    :vartype health_api: azure_web_socket_service_restapi.operations.HealthApiOperations
    :ivar web_socket_connection_api: WebSocketConnectionApiOperations operations
    :vartype web_socket_connection_api: azure_web_socket_service_restapi.operations.WebSocketConnectionApiOperations
    :param str base_url: Service URL
    :keyword int polling_interval: Default waiting time between two polls for LRO operations if no Retry-After header is present.
    """

    def __init__(
        self,
        **kwargs  # type: Any
    ):
        # type: (...) -> None
        base_url = 'None'
        self._config = AzureWebSocketServiceRESTAPIConfiguration(**kwargs)
        self._client = PipelineClient(base_url=base_url, config=self._config, **kwargs)

        client_models = {}
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)

        self.health_api = HealthApiOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.web_socket_connection_api = WebSocketConnectionApiOperations(
            self._client, self._config, self._serialize, self._deserialize)

    def close(self):
        # type: () -> None
        self._client.close()

    def __enter__(self):
        # type: () -> AzureWebSocketServiceRESTAPI
        self._client.__enter__()
        return self

    def __exit__(self, *exc_details):
        # type: (Any) -> None
        self._client.__exit__(*exc_details)
