# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6262, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._azure_web_socket_service_restapi_async import AzureWebSocketServiceRESTAPI
__all__ = ['AzureWebSocketServiceRESTAPI']
