# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.0.6262, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from typing import Any

from azure.core import AsyncPipelineClient
from msrest import Deserializer, Serializer

from ._configuration_async import AzureWebSocketServiceRESTAPIConfiguration
from .operations_async import HealthApiOperations
from .operations_async import WebSocketConnectionApiOperations


class AzureWebSocketServiceRESTAPI(object):
    """AzureWebSocketServiceRESTAPI.

    :ivar health_api: HealthApiOperations operations
    :vartype health_api: azure_web_socket_service_restapi.aio.operations_async.HealthApiOperations
    :ivar web_socket_connection_api: WebSocketConnectionApiOperations operations
    :vartype web_socket_connection_api: azure_web_socket_service_restapi.aio.operations_async.WebSocketConnectionApiOperations
    :param str base_url: Service URL
    :keyword int polling_interval: Default waiting time between two polls for LRO operations if no Retry-After header is present.
    """

    def __init__(
        self,
        **kwargs: Any
    ) -> None:
        base_url = 'None'
        self._config = AzureWebSocketServiceRESTAPIConfiguration(**kwargs)
        self._client = AsyncPipelineClient(base_url=base_url, config=self._config, **kwargs)

        client_models = {}
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)

        self.health_api = HealthApiOperations(
            self._client, self._config, self._serialize, self._deserialize)
        self.web_socket_connection_api = WebSocketConnectionApiOperations(
            self._client, self._config, self._serialize, self._deserialize)

    async def close(self) -> None:
        await self._client.close()

    async def __aenter__(self) -> "AzureWebSocketServiceRESTAPI":
        await self._client.__aenter__()
        return self

    async def __aexit__(self, *exc_details) -> None:
        await self._client.__aexit__(*exc_details)
